version: "3"
services:
  php-apache:
    container_name: ${PHP_CONTAINER_NAME}
    build:
      context: .
      dockerfile: ./build/app/php-apache/Dockerfile
    ports:
      - 8000:80
    volumes:
      - ./src/app/laravel:/var/www/laravel
    environment:
      - LARAVEL_DB_CONNECTION=mysql
      - LARAVEL_DB_HOST=${MYSQL_CONTAINER_NAME}
      - LARAVEL_DB_PORT=3306
      - LARAVEL_DB_DATABASE=${DB_NAME}
      - LARAVEL_DB_USERNAME=${DB_USER}
      - LARAVEL_DB_PASSWORD=${DB_PASSWORD}
    networks:
      - default

  mysql:
    container_name: ${MYSQL_CONTAINER_NAME}
    build:
      context: .
      dockerfile: ./build/db/mysql/Dockerfile
    ports:
      - 3306:3306
    volumes:
      - ./db/mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    networks:
      - default


  phpmyadmin:
    container_name: phpmyadmin
    build:
      context: .
      dockerfile: ./build/app/phpmyadmin/Dockerfile
    ports:
    - 7070:80
    environment:
    - PMA_ARBITRARY=1
    - PMA_HOSTS=${MYSQL_CONTAINER_NAME}:3306
    - PMA_USER=${DB_USER}
    - PMA_PASSWORD=${DB_PASSWORD}
    depends_on:
    - mysql
    networks:
      - default

networks:
  default:
    external: false
